name: DeploY CI

on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    # container:
    #   image: node:16

    steps:
    - uses: actions/checkout@v3

    - name: Setup Node...
      uses: actions/setup-node@v3
      with:
        node-version: '16.14.2'
    - name: Installing...
      run: npm ci

    - name: Building...
      run: npm run build --if-present

    - name: Deploying...
      uses: easingthemes/ssh-deploy@v2.1.5
      env:
        SSH_PRIVATE_KEY: ${{ secrets.SSH_Key }}
        ARGS: '-rltgoDzvO --delete'
        SOURCE: "dist/ " # 将要复制到云服务器的静态文件夹
        REMOTE_HOST: "47.110.162.113" # 云服务器公网地址
        REMOTE_USER: "root" # 服务器用户名
        TARGET: "/www/wwwroot/asw.limkim.cn" # 打包后的文件夹将放在目录
